export const DYJD_COLOR = '#ffbd24';
export const PLEDGED_COLOR_LIGHT = '#8982c2';
export const PLEDGED_COLOR_DARK = '#554d91';
export const MISSING_MEMBER_COLOR = '#b14038';
export const STATUS_WON = 'Winner';
export const STATUS_NOMINEE = 'Nominee';
export const STATUS_ACTIVE = 'Active Primary Candidate';
export const INCLUDE_STATUS = [STATUS_NOMINEE, STATUS_WON];
export const STILL_ACTIVE = [STATUS_ACTIVE, STATUS_NOMINEE, STATUS_WON];
